[project]
authors = ["Jacob Wujciak-Jens <jacob@wujciak.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "action-list-poc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
pyyaml = ">=6.0.2,<7"
