name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  dummy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: geekyeggo/delete-artifact@v5
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      - uses: seanmiddleditch/gha-setup-ninja@v5