name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  dummy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: hashicorp/setup-terraform@v2
      - uses: opentofu/setup-opentofu@v1
      - uses: helm/chart-testing-action@v2.5.0
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36