name: Remove Expired Refs
on:
  schedule:
    - cron: "4 2 * * *"

  pull_request:
    paths:
      - ".github/workflows/remove_expired.yml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          # Use PAT so the commit triggers other actions
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update list.yml
        shell: python
        run: |
          import sys
          sys.path.append(".")

          import gateway as g
          g.clean_list("list.yml")
          g.update_patterns("approved_patterns.yml", "list.yml")

      - name: Commit and push changes
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add list.yml approved_patterns.yml
          git commit -m "Update Actions" || echo "No changes"
          git push origin
