name: Update Dummy workflow 
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "actions.yml"
  pull_request:
    paths:
      - ".github/workflows/update_dummy.yml"
      - "actions.yml"

permissions:
  contents: read

# We want workflows on main to run in order to avoid losing data through race conditions
concurrency: "${{ github.ref }}-${{ github.workflow }}"

jobs:
  update:
    name: Update Workflow 
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update Workflow 
        shell: python
        run: |
          import sys
          sys.path.append(".")

          import gateway as g
          g.update_workflow(".github/workflows/dummy.yml", "actions.yml")
          g.update_patterns("approved_patterns.yml", "actions.yml")

      - name: Commit and push changes
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -f .github/workflows/dummy.yml approved_patterns.yml
          git commit -m "Update Workflow" || echo "No changes"
          git push origin
