name: Handle updated refs
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows.dummy.yml"
  pull_request:
    paths:
      - ".github/workflows.dummy.yml"

permissions:
  contents: read

# We want workflows on main to run in order to avoid losing data through race conditions
concurrency: "${{ github.ref }}-${{ github.workflow }}"

jobs:
  update_list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Update list.yml
        shell: python
        run: |
          import gateway as g
          g.update_list(".github/workflows/dummy.yml", "list.yml")
          g.create_pattern("approved_patterns.yml", "list.yml")

      - name: Commit and push changes
        if: ${{ github.even_name == 'push' }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add list.yml approved_patterns.yml
          git commit -m "Update Actions" || echo "No changes"
          git push origin
